version: '3.5'
networks:
  stream-net:
    name: stream-net
services:
  spark-master:
    image: bde2020/spark-master:2.4.5
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - stream-net
  spark-worker-1:
    image: bde2020/spark-master:2.4.5
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - stream-net
#  transaction-streamer-processor:
#    image: dipakpravin87/spark-streamer:final
#    container_name: transaction-streamer-processor
#    ports :
#      - "6060:6060"
#    depends_on:
#      - spark-worker-1
#      - kafka
#    links:
#      - spark-master:spark-master

